### ISSUE TITLE
Provide an option to limit the max balance of a pool

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1147]
Given #1146 , we should provide the pool operator the option to limit the maximum pool balance by pledges.

**Comment by azarovh** [comment]
As far as I understand we want to be able to limit total delegations balance so that pool stays "reward-optimal" relative to its pledge. To achieve that we can add new optional limit field to `StakePoolData` for initial value. Additionally we can provide an operation like `SetTotalDelegationsBalanceLimit` that an operator can execute at any moment later. 
If a delegator tries to delegate to that pool over the limit it will result in an error. At the same time pledge can be increased as well as reward distributed among delegators (increasing total delegation balance over the limit). Is that how you see it?

P.S. also it just occurred to me that there is no way to add more pledge to the pool

**Comment by azarovh** [comment]
I don't think it's in operator's interest to introduce such a limit. 
It's way more beneficial for a pool to attract new delegators than to try to keep 1:1 pledge to delegation ratio. 
So from operator's perspective it's incentivised to attract as many delegators as possible and additionally keep up pledging the half of pool's size. 
Delegators would seek for a pool that is almost 1:1 where they can fill the last piece of share to make pool optimal. They will likely leave if the operator won't pledge its half.
So I don't see where the limit is useful.

**Comment by azarovh** [comment]
What we should add is the way for an operator to pledge additionally.  Though it has its own risks for an operator because delegators can easily leave ruining the balance and there is no way for an operator to decrease pledge to mitigate that except decommissioning (should it be changed too?).
