### ISSUE TITLE
Deal with `OP_CODESEPARATOR`

### ISSUE THREAD

**Issue by iljakuklic** [mintlayer/mintlayer-core#171]
Have to decide on behaviour of the instruction in Scripts. Most likely just disable it.

**Comment by TheQuantumPhysicist** [comment]
Seems like it's been officially killed on multiple levels... especially with the presence of taproot

https://bitcoinops.org/en/topics/op_codeseparator/

Even transactions relaying with it won't work.

I think we should drop it and move on. It seems that with the presence of taproot, it's useless because two leaves can simulate its effect anyway.

About our bitcoin script, we can consider enabling it there (which is another discussion). But for standard formats, I don't see why we would go through this. 

I hope I'm not missing something big.

**Comment by iljakuklic** [comment]
Yep, that is my impression as well. I haven't seen a compelling example of its use anywhere. In addition to that, [miniscript](https://bitcoin.sipa.be/miniscript/) does not support `OP_CODESEPARATOR` either, as a further indication it's not deemed a well-behaved operation.
