### ISSUE TITLE
Add RPC authentication

### ISSUE THREAD

**Issue by iljakuklic** [mintlayer/mintlayer-core#192]
At the moment, anyone able to establish a connection is able to send RPC command. Some form of authentication should be added.

**Comment by TheQuantumPhysicist** [comment]
Keep in mind also that we want to support cookie authentication. A cookie is basically a temporary authentication file generated if no username/password are specified for RPC. On launch, the node creates the file `.cookie` in the data directory, which has a random username and password in the format `username:password` (completely generated at random) in one line. 

When functional tests need to use the node it just reads the cookie file and parses it, or when a user wants to run a quick RPC command with curl, then they just pipe `$(cat ~/.mintlayer/.cookie)` to their command and it just works without caring what the username/password are, since http rpc typically uses `username:password` as the format of inline authentication.

This file is created on every launch, and is only accepted as means for authentication if no username and password for RPC are specified.

**Comment by TheQuantumPhysicist** [comment]
It seems that jsonrpsee doesn't support authentication at all.

While jsonrpsee doesn't support authentication, the way to do it is by adding an authentication layer, that acts as a reverse-proxy, using the tower framework. An example of this is the [authentication layer](https://docs.rs/tower-http/latest/tower_http/auth/struct.AddAuthorizationLayer.html). 

The problem with this approach is that we, kind of, have to reimplement the http/websocket servers ourselves. Currently, the way it works is:

```
socket port -> jsonrpsee -> function handler
```

But it has to become:

```
socket port -> authentication layer -> jsonrpsee -> function handler
```

The reason we call it "reimplement" is that this is basically [what jsonrpsee did in their source code](https://github.com/paritytech/jsonrpsee/blob/18ee2122ec84392c915bfe26bea73c30f41a7a6d/server/src/server.rs). We can see that the authentication layer is just a specialization of that. We have to implement the socket and everything around it, and jsonrpsee will become just a function handler. At this point, I'm just wondering whether we should just use some web framework from scratch like ActixWeb and do this whole thing ourselves.

Pros:
- Full control to add all the features we need
- Less bloat and less fragmentation in the code

Cons:
- More time to do this right and more code to manage
- We may have to reimplement the macro magic of jsonrpsee to generate function mapping.

Two more things will make this whole problem much more complex, and we should consider this while thinking of a solution:

1. End-to-end encryption for RPC, if we want to implement that and not rely on the user's discretion
2. pub-sub for websocket. See [this example](https://github.com/paritytech/jsonrpsee/blob/18ee2122ec84392c915bfe26bea73c30f41a7a6d/examples/examples/ws_pubsub_broadcast.rs). It will make more sense to use websocket pub-sub instead of continuous polling for interested parties.
