### ISSUE TITLE
Shall we have unique tokens names?

### ISSUE THREAD

**Issue by sinitcin** [mintlayer/mintlayer-core#384]
We spoke a lot about cases like when someone can send some token (USDT for example), but it wouldn't be original USDT. There is might be a place for fraud.  

Also, NEAR blockchain require unique names for tokens. And they have native tokens, similar to ours. 

However, Ethereum allows using the same names for different tokens, and the only thing that makes your token unique is its address. Usually, tokens on Ethereum, essentially a smart contract.

**Comment by muursh** [comment]
I wouldn't say fraud/identically named tokens is really our concern here, and even if we had unique names it doesn't solve the issue. What happens if I go and create USDT the second the mainnet goes live? I now have the "USDT" name if we have unique tokens, we haven't prevented anything at all. If someone has an issue with someone else "stealing" their name then that's very much their issue rather than ours.

My original comment the other day was just about removing USDT/USDC from our tests and using more generic names.

**Comment by sinitcin** [comment]
> I wouldn't say fraud/identically named tokens is really our concern here, and even if we had unique names it doesn't solve the issue. What happens if I go and create USDT the second the mainnet goes live? I now have the "USDT" name if we have unique tokens, we haven't prevented anything at all. If someone has an issue with someone else "stealing" their name then that's very much their issue rather than ours.

Ok, then we stick on with only `token_id` make unique our tokens? And we can close the issue.

> My original comment the other day was just about removing USDT/USDC from our tests and using more generic names.

No worries. It came up from Sam's comments: https://github.com/mintlayer/mintlayer-core/pull/269#discussion_r946467123

**Comment by muursh** [comment]
> Ok, then we stick on with only token_id make unique our tokens? And we can close the issue.
Well that's arguably a different question. There's no benefit to doing so for "fraud" reasons.

**Comment by TheQuantumPhysicist** [comment]
OK. So we're deciding that token ticker uniqueness is not a requirement. I'm closing this.
